/* TeensyTalkV2.ino
   Text-to-Speech using eSpeak-ng derived G2P rules + MBROLA us2 phoneme WAVs.

         Improvements over V1:
            - Proper letter-to-sound rule engine (derived from eSpeak-ng en_rules)
               - Exception dictionary for common irregular words (binary search)
                  - MBROLA us2 phoneme WAV files (recorded human voice, 16000 Hz)
                     - Proper word tokenization and text normalization
                        - No more hand-coded character-by-character switch statement
                           - Fixed sayNumber() typo ("thousand" not "thousdand")
                              - Extended sayNumber() to handle millions
                                 - Serial debug output shows phoneme sequence for each word

                                    Hardware: Teensy 3.2/3.5/3.6/4.0/4.1 + Teensy Audio Shield
                                       Audio: MBROLA us2 WAV files at 16000 Hz on SD card
                                          Library: Frank Boesing's Teensy-WavePlayer
                                                       https://github.com/FrankBoesing/Teensy-WavePlayer

                                                          SD Card contents required:
                                                             - One WAV file per MBROLA us2 phoneme (see tts_phonemes.h for filenames)
                                                                - All files at 16000 Hz, 16-bit, mono

                                                                   Branch: espeak-ng-rewrite
                                                                      Created: 2026
                                                                      */

                                                                      #include <Audio.h>
                                                                      #include <Wire.h>
                                                                      #include <SPI.h>
                                                                      #include <SD.h>
                                                                      #include <SerialFlash.h>
                                                                      #include <play_wav.h> // https://github.com/FrankBoesing/Teensy-WavePlayer

                                                                      // Teensy 4.x I2S frequency control
                                                                      #if defined(__IMXRT1062__)
                                                                        #define T4
                                                                          #include <utility/imxrt_hw.h>
                                                                          #else
                                                                            #define F_I2S ((((I2S0_MCR >> 24) & 0x03) == 3) ? F_PLL : F_CPU)
                                                                            #endif

                                                                            // Audio objects - generated by Teensy Audio Tool
                                                                            AudioPlayWav         playWav1;
                                                                            AudioOutputI2S       outputsound;
                                                                            AudioConnection      patchCord1(playWav1, 0, outputsound, 0);
                                                                            AudioConnection      patchCord2(playWav1, 0, outputsound, 1);
                                                                            AudioControlSGTL5000 sgtl5000_1;

                                                                            // SD card pins (Audio Shield)
                                                                            #define SDCARD_CS_PIN   10
                                                                            #define SDCARD_MOSI_PIN  7
                                                                            #define SDCARD_SCK_PIN  14

                                                                            // Include TTS modules in dependency order
                                                                            #include "tts_phonemes.h"  // phoneme->WAV mapping + playPhoneme()
                                                                            #include "tts_dict.h"      // exception dictionary + dictLookup()
                                                                            #include "tts_rules.h"     // letter-to-sound rules + applyRules()
                                                                            #include "tts_say.h"       // say(), sayNumber(), speakWord()

                                                                            // ---------------------------------------------------------------
                                                                            // I2S frequency control (unchanged from V1)
                                                                            // ---------------------------------------------------------------
                                                                            #ifdef T4
                                                                            #else
                                                                            uint32_t I2S_dividers(float fsamp, uint32_t nbits, uint32_t tcr2_div) {
                                                                              unsigned fract, divi;
                                                                                fract = divi = 1;
                                                                                  float minfehler = 1e7;
                                                                                    unsigned x = (nbits * ((tcr2_div + 1) * 2));
                                                                                      unsigned b = F_I2S / x;
                                                                                        for (unsigned i = 1; i < 256; i++) {
                                                                                            unsigned d = round(b / fsamp * i);
                                                                                                float freq = b * i / (float)d;
                                                                                                    float fehler = fabs(fsamp - freq);
                                                                                                        if (fehler < minfehler && d < 4096) {
                                                                                                              fract = i; divi = d; minfehler = fehler;
                                                                                                                    if (fehler == 0.0f) break;
                                                                                                                        }
                                                                                                                          }
                                                                                                                            return I2S_MDR_FRACT((fract - 1)) | I2S_MDR_DIVIDE((divi - 1));
                                                                                                                            }
                                                                                                                            #endif
                                                                                                                            
                                                                                                                            void setI2SFreq(int freq) {
                                                                                                                            #if defined(T4)
                                                                                                                              int n1 = 4;
                                                                                                                                int n2 = 1 + (24000000 * 27) / (freq * 256 * n1);
                                                                                                                                  double C = ((double)freq * 256 * n1 * n2) / 24000000;
                                                                                                                                    int c0 = C;
                                                                                                                                      int c2 = 10000;
                                                                                                                                        int c1 = C * c2 - (c0 * c2);
                                                                                                                                          set_audioClock(c0, c1, c2, true);
                                                                                                                                            CCM_CS1CDR = (CCM_CS1CDR & ~(CCM_CS1CDR_SAI1_CLK_PRED_MASK | CCM_CS1CDR_SAI1_CLK_PODF_MASK))
                                                                                                                                                         | CCM_CS1CDR_SAI1_CLK_PRED(n1 - 1)
                                                                                                                                                                      | CCM_CS1CDR_SAI1_CLK_PODF(n2 - 1);
                                                                                                                                                                      #else
                                                                                                                                                                        unsigned tcr5 = I2S0_TCR5;
                                                                                                                                                                          unsigned word0width = ((tcr5 >> 24) & 0x1f) + 1;
                                                                                                                                                                            unsigned wordnwidth = ((tcr5 >> 16) & 0x1f) + 1;
                                                                                                                                                                              unsigned framesize = ((I2S0_TCR4 >> 16) & 0x0f) + 1;
                                                                                                                                                                                unsigned nbits = word0width + wordnwidth * (framesize - 1);
                                                                                                                                                                                  unsigned tcr2div = I2S0_TCR2 & 0xff;
                                                                                                                                                                                    uint32_t MDR = I2S_dividers(freq, nbits, tcr2div);
                                                                                                                                                                                      if (MDR > 0) {
                                                                                                                                                                                          while (I2S0_MCR & I2S_MCR_DUF) { ; }
                                                                                                                                                                                              I2S0_MDR = MDR;
                                                                                                                                                                                                }
                                                                                                                                                                                                #endif
                                                                                                                                                                                                }
                                                                                                                                                                                                
                                                                                                                                                                                                // ---------------------------------------------------------------
                                                                                                                                                                                                // setup()
                                                                                                                                                                                                // ---------------------------------------------------------------
                                                                                                                                                                                                void setup() {
                                                                                                                                                                                                  Serial.begin(9600);
                                                                                                                                                                                                  
                                                                                                                                                                                                    AudioMemory(10);
                                                                                                                                                                                                      sgtl5000_1.enable();
                                                                                                                                                                                                        sgtl5000_1.volume(0.6);
                                                                                                                                                                                                        
                                                                                                                                                                                                          // SD card init - board-specific
                                                                                                                                                                                                          #if defined(ARDUINO_TEENSY41) || defined(ARDUINO_TEENSY36)
                                                                                                                                                                                                            if (!SD.begin(BUILTIN_SDCARD)) {
                                                                                                                                                                                                                while (1) { Serial.println("SD card failed"); delay(500); }
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                  #elif defined(ARDUINO_TEENSY40) || defined(ARDUINO_TEENSY32)
                                                                                                                                                                                                                    SPI.setMOSI(SDCARD_MOSI_PIN);
                                                                                                                                                                                                                      SPI.setSCK(SDCARD_SCK_PIN);
                                                                                                                                                                                                                        if (!SD.begin(SDCARD_CS_PIN)) {
                                                                                                                                                                                                                            while (1) { Serial.println("SD card failed"); delay(500); }
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                              #endif
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                // MBROLA us2 is 16000 Hz - no resampling needed
                                                                                                                                                                                                                                  setI2SFreq(16000);
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    Serial.println("TeensyTalk V2 ready.");
                                                                                                                                                                                                                                      Serial.println("MBROLA us2 phonemes, eSpeak-ng G2P rules.");
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      // ---------------------------------------------------------------
                                                                                                                                                                                                                                      // loop() - demo, mirrors original TeensyTalk demo content
                                                                                                                                                                                                                                      // ---------------------------------------------------------------
                                                                                                                                                                                                                                      void loop() {
                                                                                                                                                                                                                                        delay(1000);
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          long altitude = random(1, 9999);
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                            say("the height is", playWav1);
                                                                                                                                                                                                                                              delay(100);
                                                                                                                                                                                                                                                sayNumber(altitude, playWav1);
                                                                                                                                                                                                                                                  delay(75);
                                                                                                                                                                                                                                                    say("feet", playWav1);
                                                                                                                                                                                                                                                      delay(200);
                                                                                                                                                                                                                                                        say("or", playWav1);
                                                                                                                                                                                                                                                          sayNumber(altitude / 3, playWav1);
                                                                                                                                                                                                                                                            delay(75);
                                                                                                                                                                                                                                                              say("meters", playWav1);
                                                                                                                                                                                                                                                                delay(300);
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  say("north west south east", playWav1);
                                                                                                                                                                                                                                                                    delay(200);
                                                                                                                                                                                                                                                                      say("up down turn left turn right on off", playWav1);
                                                                                                                                                                                                                                                                        delay(2000);
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                          say("resistance is futile", playWav1);
                                                                                                                                                                                                                                                                            delay(1000);
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              say("your off to great places. today is your day.", playWav1);
                                                                                                                                                                                                                                                                                delay(5000);
                                                                                                                                                                                                                                                                                }
