// tts_dict.h
// Hardcoded exception dictionary for TeensyTalk V2.
// Words that eSpeak-ng rules would mispronounce are listed here.
// Phoneme strings use MBROLA us2 phoneme names, space-separated.
// Dictionary MUST remain in alphabetical order for binary search.
// Source: eSpeak-ng dictsource/en_list (most common irregular words)

#ifndef TTS_DICT_H
#define TTS_DICT_H

struct DictEntry {
  const char* word;
  const char* phonemes; // space-separated MBROLA us2 phoneme names
};

// Binary search - dict MUST be alphabetically sorted by word
static const DictEntry EXCEPTION_DICT[] = {
{ "a",          "{"              },
{ "about",      "{ b aU t"       },
{ "after",      "{ f t r="       },
{ "again",      "{ g E n"        },
{ "against",    "{ g E n s t"    },
{ "ago",        "{ g @U"         },
{ "air",        "E r"            },
{ "all",        "O l"            },
{ "also",       "O l s @U"       },
{ "always",     "O l w EI z"     },
{ "an",         "{ n"            },
{ "and",        "{ n d"          },
{ "any",        "E n i"          },
{ "are",        "A r"            },
{ "as",         "{ z"            },
{ "asked",      "{ s k t"        },
{ "at",         "{ t"            },
{ "away",       "{ w EI"         },
{ "be",         "b i"            },
{ "been",       "b I n"          },
{ "both",       "b @U T"         },
{ "build",      "b I l d"        },
{ "built",      "b I l t"        },
{ "but",        "b V t"          },
{ "by",         "b AI"           },
{ "call",       "k O l"          },
{ "called",     "k O l d"        },
{ "came",       "k EI m"         },
{ "can",        "k { n"          },
{ "come",       "k V m"          },
{ "could",      "k U d"          },
{ "do",         "d u"            },
{ "does",       "d V z"          },
{ "done",       "d V n"          },
{ "door",       "d Or"           },
{ "down",       "d aU n"         },
{ "each",       "i tS"           },
{ "eight",      "EI t"           },
{ "even",       "i v @n"         },
{ "every",      "E v r i"        },
{ "eye",        "AI"             },
{ "eyes",       "AI z"           },
{ "few",        "f j u"          },
{ "find",       "f AI n d"       },
{ "five",       "f AI v"         },
{ "floor",      "f l Or"         },
{ "for",        "f @"            },
{ "four",       "f Or"           },
{ "from",       "f r V m"        },
{ "front",      "f r V n t"      },
{ "get",        "g E t"          },
{ "give",       "g I v"          },
{ "given",      "g I v @n"       },
{ "go",         "g @U"           },
{ "gone",       "g O n"          },
{ "good",       "g U d"          },
{ "got",        "g A t"          },
{ "great",      "g r EI t"       },
{ "group",      "g r u p"        },
{ "had",        "h { d"          },
{ "hand",       "h { n d"        },
{ "has",        "h { z"          },
{ "have",       "h { v"          },
{ "he",         "h i"            },
{ "head",       "h E d"          },
{ "heard",      "h r= d"         },
{ "her",        "h r="           },
{ "here",       "h I r"          },
{ "high",       "h AI"           },
{ "him",        "h I m"          },
{ "his",        "h I z"          },
{ "home",       "h @U m"         },
{ "hour",       "aU r"           },
{ "hours",      "aU r z"         },
{ "how",        "h aU"           },
{ "I",          "AI"             },
{ "if",         "I f"            },
{ "in",         "I n"            },
{ "into",       "I n t u"        },
{ "is",         "I z"            },
{ "it",         "I t"            },
{ "its",        "I t s"          },
{ "just",       "dZ V s t"       },
{ "keep",       "k i p"          },
{ "kind",       "k AI n d"       },
{ "knew",       "n j u"          },
{ "know",       "n @U"           },
{ "known",      "n @U n"         },
{ "large",      "l A r dZ"       },
{ "last",       "l { s t"        },
{ "learn",      "l r= n"         },
{ "left",       "l E f t"        },
{ "life",       "l AI f"         },
{ "like",       "l AI k"         },
{ "little",     "l I 4 @l"       },
{ "live",       "l I v"          },
{ "long",       "l O N"          },
{ "look",       "l U k"          },
{ "love",       "l V v"          },
{ "made",       "m EI d"         },
{ "make",       "m EI k"         },
{ "man",        "m { n"          },
{ "many",       "m E n i"        },
{ "may",        "m EI"           },
{ "me",         "m i"            },
{ "mean",       "m i n"          },
{ "men",        "m E n"          },
{ "might",      "m AI t"         },
{ "more",       "m Or"           },
{ "most",       "m @U s t"       },
{ "mother",     "m V D r="       },
{ "move",       "m u v"          },
{ "much",       "m V tS"         },
{ "my",         "m AI"           },
{ "name",       "n EI m"         },
{ "never",      "n E v r="       },
{ "new",        "n j u"          },
{ "nine",       "n AI n"         },
{ "no",         "n @U"           },
{ "not",        "n A t"          },
{ "nothing",    "n V T I N"      },
{ "now",        "n aU"           },
{ "number",     "n V m b r="     },
{ "of",         "V v"            },
{ "off",        "O f"            },
{ "often",      "O f @n"         },
{ "old",        "@U l d"         },
{ "on",         "A n"            },
{ "once",       "w V n s"        },
{ "one",        "w V n"          },
{ "only",       "@U n l i"       },
{ "open",       "@U p @n"        },
{ "or",         "Or"             },
{ "other",      "V D r="         },
{ "our",        "aU r"           },
{ "out",        "aU t"           },
{ "over",       "@U v r="        },
{ "own",        "@U n"           },
{ "part",       "p A r t"        },
{ "people",     "p i p @l"       },
{ "place",      "p l EI s"       },
{ "point",      "p OI n t"       },
{ "put",        "p U t"          },
{ "read",       "r i d"          },
{ "right",      "r AI t"         },
{ "said",       "s E d"          },
{ "same",       "s EI m"         },
{ "saw",        "s O"            },
{ "say",        "s EI"           },
{ "school",     "s k u l"        },
{ "sea",        "s i"            },
{ "second",     "s E k @n d"     },
{ "see",        "s i"            },
{ "seem",       "s i m"          },
{ "set",        "s E t"          },
{ "seven",      "s E v @n"       },
{ "she",        "S i"            },
{ "should",     "S U d"          },
{ "show",       "S @U"           },
{ "six",        "s I k s"        },
{ "small",      "s m O l"        },
{ "so",         "s @U"           },
{ "some",       "s V m"          },
{ "something",  "s V m T I N"    },
{ "sound",      "s aU n d"       },
{ "still",      "s t I l"        },
{ "such",       "s V tS"         },
{ "take",       "t EI k"         },
{ "tell",       "t E l"          },
{ "ten",        "t E n"          },
{ "than",       "D { n"          },
{ "that",       "D { t"          },
{ "the",        "D @"            },
{ "their",      "D E r"          },
{ "them",       "D E m"          },
{ "then",       "D E n"          },
{ "there",      "D E r"          },
{ "these",      "D i z"          },
{ "they",       "D EI"           },
{ "think",      "T I N k"        },
{ "this",       "D I s"          },
{ "those",      "D @U z"         },
{ "thought",    "T O t"          },
{ "three",      "T r i"          },
{ "through",    "T r u"          },
{ "time",       "t AI m"         },
{ "to",         "t u"            },
{ "together",   "t @ g E D r="   },
{ "told",       "t @U l d"       },
{ "too",        "t u"            },
{ "took",       "t U k"          },
{ "turn",       "t r= n"         },
{ "two",        "t u"            },
{ "under",      "V n d r="       },
{ "until",      "V n t I l"      },
{ "up",         "V p"            },
{ "us",         "V s"            },
{ "use",        "j u z"          },
{ "very",       "v E r i"        },
{ "want",       "w A n t"        },
{ "was",        "w V z"          },
{ "water",      "w O 4 r="       },
{ "way",        "w EI"           },
{ "we",         "w i"            },
{ "well",       "w E l"          },
{ "went",       "w E n t"        },
{ "were",       "w r="           },
{ "what",       "w V t"          },
{ "when",       "w E n"          },
{ "where",      "w E r"          },
{ "which",      "w I tS"         },
{ "while",      "w AI l"         },
{ "who",        "h u"            },
{ "why",        "w AI"           },
{ "will",       "w I l"          },
{ "with",       "w I D"          },
{ "word",       "w r= d"         },
{ "work",       "w r= k"         },
{ "world",      "w r= l d"       },
{ "would",      "w U d"          },
{ "write",      "r AI t"         },
{ "year",       "j I r"          },
{ "years",      "j I r z"        },
{ "you",        "j u"            },
{ "young",      "j V N"          },
{ "your",       "j Or"           },
};

static const int DICT_SIZE = sizeof(EXCEPTION_DICT) / sizeof(EXCEPTION_DICT[0]);

// Binary search the exception dictionary.
// Returns phoneme string if found, NULL if not found.
// Word must be lowercase.
static const char* dictLookup(const char* word) {
    int lo = 0, hi = DICT_SIZE - 1;
  while (lo <= hi) {
    int mid = (lo + hi) / 2;
    int cmp = strcmp(word, EXCEPTION_DICT[mid].word);
    if (cmp == 0) return EXCEPTION_DICT[mid].phonemes;
    if (cmp < 0)  hi = mid - 1;
    else          lo = mid + 1;
  }
  return NULL; // not found, fall through to rules
}

#endif // TTS_DICT_H
