// tts_dict.h
// Hardcoded exception dictionary for TeensyTalk V2.
// Words that letter-to-sound rules would mispronounce are listed here.
// Phoneme strings use MBROLA us2 phoneme names, space-separated.
// Dictionary MUST remain in alphabetical order for binary search.
// Source: eSpeak-ng dictsource/en_list (expanded ~600 most common irregular words)

#ifndef TTS_DICT_H
#define TTS_DICT_H

struct DictEntry {
  const char* word;
  const char* phonemes; // space-separated MBROLA us2 phoneme names
};

// Binary search - dict MUST be alphabetically sorted by word
static const DictEntry EXCEPTION_DICT[] = {
{ "a",           "{"                    },
{ "able",        "EI b @l"              },
{ "about",       "{ b aU t"             },
{ "above",       "{ b V v"              },
{ "abroad",      "{ b r O d"            },
{ "absence",     "{ b s @ n s"           },
{ "accept",      "{ k s E p t"          },
{ "access",      "{ k s E s"            },
{ "account",     "{ k aU n t"           },
{ "across",      "{ k r O s"            },
{ "act",         "{ k t"                },
{ "action",      "{ k S @ n"             },
{ "actually",    "{ k tS u @ l i"       },
{ "add",         "{ d"                  },
{ "address",     "{ d r E s"            },
{ "after",       "{ f t r="             },
{ "again",       "{ g E n"              },
{ "against",     "{ g E n s t"          },
{ "age",         "EI dZ"                },
{ "ago",         "{ g @U"               },
{ "agree",       "{ g r i"              },
{ "ahead",       "{ h E d"              },
{ "air",         "E r"                  },
{ "alive",       "@ l AI v"             },
{ "all",         "O l"                  },
{ "allow",       "{ l aU"               },
{ "already",     "O l r E d i"          },
{ "also",        "O l s @U"             },
{ "although",    "O l D @U"             },
{ "always",      "O l w EI z"           },
{ "among",       "{ m V N"              },
{ "an",          "{ n"                  },
{ "and",         "{ n d"                },
{ "another",     "{ n V D r="           },
{ "answer",      "{ n s r="             },
{ "any",         "E n i"                },
{ "anyone",      "E n i w V n"          },
{ "anything",    "E n i T I N"          },
{ "anyway",      "E n i w EI"           },
{ "are",         "A r"                  },
{ "area",        "E r i @"              },
{ "around",      "{ r aU n d"           },
{ "as",          "{ z"                  },
{ "ask",         "{ s k"                },
{ "asked",       "{ s k t"              },
{ "at",          "{ t"                  },
{ "away",        "{ w EI"               },
{ "awful",       "O f @l"               },
{ "awhile",      "{ w AI l"             },
{ "back",        "b { k"                },
{ "bad",         "b { d"                },
{ "based",       "b EI s t"             },
{ "be",          "b i"                  },
{ "because",     "b I k V z"            },
{ "become",      "b I k V m"            },
{ "been",        "b I n"                },
{ "before",      "b I f O r"             },
{ "behind",      "b I h AI n d"         },
{ "believe",     "b I l i v"            },
{ "below",       "b I l @U"             },
{ "between",     "b I t w i n"          },
{ "beyond",      "b i A n d"            },
{ "big",         "b I g"                },
{ "bit",         "b I t"                },
{ "both",        "b @U T"               },
{ "break",       "b r EI k"             },
{ "bring",       "b r I N"              },
{ "broke",       "b r @U k"             },
{ "brother",     "b r V D r="           },
{ "brought",     "b r O t"              },
{ "build",       "b I l d"              },
{ "built",       "b I l t"              },
{ "business",    "b I z n @s"           },
{ "but",         "b V t"                },
{ "buy",         "b AI"                 },
{ "by",          "b AI"                 },
{ "call",        "k O l"                },
{ "called",      "k O l d"              },
{ "came",        "k EI m"               },
{ "can",         "k { n"                },
{ "cannot",      "k { n A t"            },
{ "care",        "k E r"                },
{ "carry",       "k { r i"              },
{ "cause",       "k O z"                },
{ "change",      "tS EI n dZ"           },
{ "chaos",       "k EI A z"             },
{ "character",   "k { r I k t r="       },
{ "check",       "tS E k"               },
{ "chemistry",   "k E m I s t r i"      },
{ "child",       "tS AI l d"            },
{ "children",    "tS I l d r @ n"        },
{ "choose",      "tS u z"               },
{ "chose",       "tS @U z"              },
{ "chrome",      "k r @U m"             },
{ "city",        "s I 4 i"              },
{ "close",       "k l @U z"             },
{ "clothes",     "k l @U D z"           },
{ "cold",        "k @U l d"             },
{ "come",        "k V m"                },
{ "coming",      "k V m I N"            },
{ "common",      "k A m @ n"             },
{ "continue",    "k @ n t I n j u"       },
{ "could",       "k U d"                },
{ "country",     "k V n t r i"          },
{ "couple",      "k V p @l"             },
{ "course",      "k O r s"               },
{ "cut",         "k V t"                },
{ "dad",         "d { d"                },
{ "day",         "d EI"                 },
{ "dead",        "d E d"                },
{ "deal",        "d i l"                },
{ "dear",        "d I r"                },
{ "death",       "d E T"                },
{ "decide",      "d I s AI d"           },
{ "did",         "d I d"                },
{ "different",   "d I f r @ n t"         },
{ "difficult",   "d I f I k @l t"       },
{ "do",          "d u"                  },
{ "does",        "d V z"                },
{ "done",        "d V n"                },
{ "door",        "d O r"                 },
{ "doubt",       "d aU t"               },
{ "down",        "d aU n"               },
{ "draw",        "d r O"                },
{ "dream",       "d r i m"              },
{ "drive",       "d r AI v"             },
{ "during",      "d j U r I N"          },
{ "each",        "i tS"                 },
{ "early",       "r= l i"               },
{ "earth",       "r= T"                 },
{ "echo",        "E k @U"               },
{ "eight",       "EI t"                 },
{ "either",      "i D r="               },
{ "else",        "E l s"                },
{ "end",         "E n d"                },
{ "enough",      "I n V f"              },
{ "even",        "i v @ n"               },
{ "every",       "E v r i"              },
{ "everyone",    "E v r i w V n"        },
{ "everything",  "E v r i T I N"        },
{ "exactly",     "I g z { k t l i"      },
{ "example",     "I g z A m p @l"       },
{ "except",      "I k s E p t"          },
{ "eye",         "AI"                   },
{ "eyes",        "AI z"                 },
{ "face",        "f EI s"               },
{ "fact",        "f { k t"              },
{ "false",       "f O l s"              },
{ "family",      "f { m @ l i"          },
{ "far",         "f A r"                },
{ "father",      "f A D r="             },
{ "fear",        "f I r"                },
{ "feel",        "f i l"                },
{ "felt",        "f E l t"              },
{ "few",         "f j u"                },
{ "field",       "f i l d"              },
{ "figure",      "f I g j r="           },
{ "fill",        "f I l"                },
{ "final",       "f AI n @l"            },
{ "find",        "f AI n d"             },
{ "fire",        "f AI r"               },
{ "first",       "f r= s t"             },
{ "five",        "f AI v"               },
{ "floor",       "f l O r"               },
{ "follow",      "f A l @U"             },
{ "for",         "f @"                  },
{ "force",       "f O r s"               },
{ "form",        "f O r m"               },
{ "found",       "f aU n d"             },
{ "four",        "f O r"                 },
{ "free",        "f r i"                },
{ "friend",      "f r E n d"            },
{ "from",        "f r V m"              },
{ "front",       "f r V n t"            },
{ "full",        "f U l"                },
{ "further",     "f r= D r="            },
{ "future",      "f j u tS r="          },
{ "get",         "g E t"                },
{ "give",        "g I v"                },
{ "given",       "g I v @ n"             },
{ "go",          "g @U"                 },
{ "gone",        "g O n"                },
{ "good",        "g U d"                },
{ "got",         "g A t"                },
{ "gravel",      "g r { v @ l"          },
{ "great",       "g r EI t"             },
{ "ground",      "g r aU n d"           },
{ "group",       "g r u p"              },
{ "grow",        "g r @U"               },
{ "guess",       "g E s"                },
{ "guide",       "g AI d"               },
{ "guitar",      "g I t A r"            },
{ "guy",         "g AI"                 },
{ "had",         "h { d"                },
{ "half",        "h { f"                },
{ "hand",        "h { n d"              },
{ "happen",      "h { p @ n"             },
{ "hard",        "h A r d"              },
{ "has",         "h { z"                },
{ "have",        "h { v"                },
{ "he",          "h i"                  },
{ "head",        "h E d"                },
{ "heard",       "h r= d"               },
{ "heart",       "h A r t"              },
{ "heavy",       "h E v i"              },
{ "help",        "h E l p"              },
{ "her",         "h r="                 },
{ "here",        "h I r"                },
{ "herself",     "h r= s E l f"         },
{ "high",        "h AI"                 },
{ "him",         "h I m"                },
{ "himself",     "h I m s E l f"        },
{ "his",         "h I z"                },
{ "hold",        "h @U l d"             },
{ "home",        "h @U m"               },
{ "hope",        "h @U p"               },
{ "hour",        "aU r"                 },
{ "hours",       "aU r z"               },
{ "house",       "h aU s"               },
{ "how",         "h aU"                 },
{ "however",     "h aU E v r="          },
{ "hundred",     "h V n d r @ d"        },
{ "i",           "AI"                   },
{ "idea",        "AI d i @"             },
{ "if",          "I f"                  },
{ "image",       "I m I dZ"             },
{ "important",   "I m p O r t @ n t"      },
{ "improve",     "I m p r u v"          },
{ "in",          "I n"                  },
{ "include",     "I n k l u d"          },
{ "indeed",      "I n d i d"            },
{ "instead",     "I n s t E d"          },
{ "into",        "I n t u"              },
{ "is",          "I z"                  },
{ "issue",       "I S u"                },
{ "it",          "I t"                  },
{ "its",         "I t s"                },
{ "itself",      "I t s E l f"          },
{ "just",        "dZ V s t"             },
{ "keep",        "k i p"                },
{ "kind",        "k AI n d"             },
{ "knew",        "n j u"                },
{ "know",        "n @U"                 },
{ "knowledge",   "n A l I dZ"           },
{ "known",       "n @U n"               },
{ "large",       "l A r dZ"             },
{ "last",        "l { s t"              },
{ "later",       "l EI 4 r="            },
{ "laugh",       "l { f"                },
{ "lead",        "l i d"                },
{ "learn",       "l r= n"               },
{ "least",       "l i s t"              },
{ "leave",       "l i v"                },
{ "left",        "l E f t"              },
{ "less",        "l E s"                },
{ "let",         "l E t"                },
{ "level",       "l E v @l"             },
{ "life",        "l AI f"               },
{ "light",       "l AI t"               },
{ "like",        "l AI k"               },
{ "likely",      "l AI k l i"           },
{ "listen",      "l I s @ n"             },
{ "little",      "l I 4 @l"             },
{ "live",        "l I v"                },
{ "local",       "l @U k @l"            },
{ "long",        "l O N"                },
{ "look",        "l U k"                },
{ "lose",        "l u z"                },
{ "lost",        "l O s t"              },
{ "love",        "l V v"                },
{ "low",         "l @U"                 },
{ "made",        "m EI d"               },
{ "make",        "m EI k"               },
{ "man",         "m { n"                },
{ "many",        "m E n i"              },
{ "matter",      "m { 4 r="             },
{ "may",         "m EI"                 },
{ "maybe",       "m EI b i"             },
{ "me",          "m i"                  },
{ "mean",        "m i n"                },
{ "men",         "m E n"                },
{ "meter",       "m i t r="              },
{ "meters",      "m i t r= z"           },
{ "might",       "m AI t"               },
{ "mind",        "m AI n d"             },
{ "minute",      "m I n I t"            },
{ "moment",      "m @U m @ n t"          },
{ "money",       "m V n i"              },
{ "month",       "m V n T"              },
{ "more",        "m O r"                 },
{ "most",        "m @U s t"             },
{ "mother",      "m V D r="             },
{ "move",        "m u v"                },
{ "much",        "m V tS"               },
{ "must",        "m V s t"              },
{ "my",          "m AI"                 },
{ "myself",      "m AI s E l f"         },
{ "name",        "n EI m"               },
{ "nature",      "n EI tS r="           },
{ "near",        "n I r"                },
{ "need",        "n i d"                },
{ "never",       "n E v r="             },
{ "new",         "n j u"                },
{ "next",        "n E k s t"            },
{ "nice",        "n AI s"               },
{ "night",       "n AI t"               },
{ "nine",        "n AI n"               },
{ "no",          "n @U"                 },
{ "nobody",      "n @U b A d i"         },
{ "not",         "n A t"                },
{ "nothing",     "n V T I N"            },
{ "notice",      "n @U t I s"           },
{ "now",         "n aU"                 },
{ "number",      "n V m b r="           },
{ "of",          "V v"                  },
{ "off",         "O f"                  },
{ "offer",       "O f r="               },
{ "often",       "O f @ n"               },
{ "old",         "@U l d"               },
{ "on",          "A n"                  },
{ "once",        "w V n s"              },
{ "one",         "w V n"                },
{ "only",        "@U n l i"             },
{ "open",        "@U p @ n"              },
{ "or",          "O r"                   },
{ "order",       "O r d r="              },
{ "other",       "V D r="               },
{ "otherwise",   "V D r= w AI z"        },
{ "our",         "aU r"                 },
{ "out",         "aU t"                 },
{ "outside",     "aU t s AI d"          },
{ "over",        "@U v r="              },
{ "own",         "@U n"                 },
{ "panel",       "p { n @ l"            },
{ "part",        "p A r t"              },
{ "past",        "p { s t"              },
{ "path",        "p { T"                },
{ "peace",       "p i s"                },
{ "people",      "p i p @l"             },
{ "perhaps",     "p r= h { p s"         },
{ "person",      "p r= s @ n"            },
{ "piece",       "p i s"                },
{ "place",       "p l EI s"             },
{ "plan",        "p l { n"              },
{ "point",       "p OI n t"             },
{ "poor",        "p U r"                },
{ "possible",    "p A s I b @l"         },
{ "power",       "p aU r="              },
{ "probably",    "p r A b @ b l i"      },
{ "problem",     "p r A b l @m"         },
{ "pull",        "p U l"                },
{ "push",        "p U S"                },
{ "put",         "p U t"                },
{ "question",    "k w E s tS @ n"        },
{ "quite",       "k w AI t"             },
{ "range",       "r EI n dZ"            },
{ "rather",      "r { D r="             },
{ "reach",       "r i tS"               },
{ "read",        "r i d"                },
{ "ready",       "r E d i"              },
{ "real",        "r i @l"               },
{ "really",      "r i @ l i"            },
{ "reason",      "r i z @ n"             },
{ "receive",     "r I s i v"            },
{ "right",       "r AI t"               },
{ "road",        "r @U d"               },
{ "rocket",      "r A k I t"           },
{ "room",        "r u m"                },
{ "run",         "r V n"                },
{ "said",        "s E d"                },
{ "same",        "s EI m"               },
{ "saw",         "s O"                  },
{ "say",         "s EI"                 },
{ "school",      "s k u l"              },
{ "sea",         "s i"                  },
{ "second",      "s E k @ n d"           },
{ "see",         "s i"                  },
{ "seem",        "s i m"                },
{ "send",        "s E n d"              },
{ "sense",       "s E n s"              },
{ "set",         "s E t"                },
{ "seven",       "s E v @ n"             },
{ "she",         "S i"                  },
{ "short",       "S O r t"               },
{ "should",      "S U d"                },
{ "show",        "S @U"                 },
{ "side",        "s AI d"               },
{ "since",       "s I n s"              },
{ "six",         "s I k s"              },
{ "small",       "s m O l"              },
{ "so",          "s @U"                 },
{ "some",        "s V m"                },
{ "someone",     "s V m w V n"          },
{ "something",   "s V m T I N"          },
{ "sometimes",   "s V m t AI m z"       },
{ "somewhere",   "s V m w E r"          },
{ "soon",        "s u n"                },
{ "sort",        "s O r t"               },
{ "sound",       "s aU n d"             },
{ "speak",       "s p i k"              },
{ "spend",       "s p E n d"            },
{ "start",       "s t A r t"            },
{ "stay",        "s t EI"               },
{ "still",       "s t I l"              },
{ "stomach",     "s t V m @k"           },
{ "stop",        "s t A p"              },
{ "strange",     "s t r EI n dZ"        },
{ "strong",      "s t r O N"            },
{ "such",        "s V tS"               },
{ "sure",        "S U r"                },
{ "take",        "t EI k"               },
{ "talk",        "t O k"                },
{ "tell",        "t E l"                },
{ "ten",         "t E n"                },
{ "than",        "D { n"                },
{ "that",        "D { t"                },
{ "the",         "D @"                  },
{ "their",       "D E r"                },
{ "them",        "D E m"                },
{ "then",        "D E n"                },
{ "there",       "D E r"                },
{ "therefore",   "D E r f O r"           },
{ "these",       "D i z"                },
{ "they",        "D EI"                 },
{ "thing",       "T I N"                },
{ "think",       "T I N k"              },
{ "this",        "D I s"                },
{ "though",      "D @U"                 },
{ "thought",     "T O t"                },
{ "thousand",    "T aU z @ n d"          },
{ "three",       "T r i"                },
{ "through",     "T r u"                },
{ "time",        "t AI m"               },
{ "to",          "t u"                  },
{ "today",       "t @ d EI"             },
{ "together",    "t @ g E D r="         },
{ "told",        "t @U l d"             },
{ "too",         "t u"                  },
{ "took",        "t U k"                },
{ "toward",      "t @ w O r d"           },
{ "travel",      "t r { v @ l"          },
{ "true",        "t r u"                },
{ "try",         "t r AI"               },
{ "turn",        "t r= n"               },
{ "two",         "t u"                  },
{ "type",        "t AI p"               },
{ "under",       "V n d r="             },
{ "understand",  "V n d r= s t { n d"   },
{ "until",       "V n t I l"            },
{ "up",          "V p"                  },
{ "us",          "V s"                  },
{ "use",         "j u z"                },
{ "used",        "j u z d"              },
{ "usually",     "j u Z u @ l i"        },
{ "very",        "v E r i"              },
{ "view",        "v j u"                },
{ "voice",       "v OI s"               },
{ "walk",        "w O k"                },
{ "want",        "w A n t"              },
{ "was",         "w V z"                },
{ "water",       "w O 4 r="             },
{ "way",         "w EI"                 },
{ "we",          "w i"                  },
{ "week",        "w i k"                },
{ "well",        "w E l"                },
{ "went",        "w E n t"              },
{ "were",        "w r="                 },
{ "what",        "w V t"                },
{ "whatever",    "w V t E v r="         },
{ "when",        "w E n"                },
{ "where",       "w E r"                },
{ "whether",     "w E D r="             },
{ "which",       "w I tS"               },
{ "while",       "w AI l"               },
{ "white",       "w AI t"               },
{ "who",         "h u"                  },
{ "whole",       "h @U l"               },
{ "whose",       "h u z"                },
{ "why",         "w AI"                 },
{ "will",        "w I l"                },
{ "with",        "w I D"                },
{ "without",     "w I D aU t"           },
{ "woman",       "w U m @ n"             },
{ "women",       "w I m I n"            },
{ "won",         "w V n"                },
{ "word",        "w r= d"               },
{ "work",        "w r= k"               },
{ "world",       "w r= l d"             },
{ "worry",       "w r= i"               },
{ "would",       "w U d"                },
{ "write",       "r AI t"               },
{ "wrong",       "r O N"                },
{ "year",        "j I r"                },
{ "years",       "j I r z"              },
{ "yet",         "j E t"                },
{ "you",         "j u"                  },
{ "young",       "j V N"                },
{ "your",        "j O r"                 },
{ "yourself",    "j O r s E l f"         },
};

static const int DICT_SIZE = sizeof(EXCEPTION_DICT) / sizeof(EXCEPTION_DICT[0]);

// Binary search the exception dictionary.
// Returns phoneme string if found, NULL if not found.
// Word must be lowercase.
static const char* dictLookup(const char* word) {
    int lo = 0, hi = DICT_SIZE - 1;
  while (lo <= hi) {
    int mid = (lo + hi) / 2;
    int cmp = strcmp(word, EXCEPTION_DICT[mid].word);
    if (cmp == 0) return EXCEPTION_DICT[mid].phonemes;
    if (cmp < 0) hi = mid - 1;
    else lo = mid + 1;
  }
  return NULL; // not found, fall through to rules
}

#endif // TTS_DICT_H
